/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {


    public static void main(String[] args) {
        Motor m = new Motor("helice");
        Aviao a = new Aviao();

    }
}
