/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Aldeao a = new Aldeao(25,1,0.8);
        Arqueiro r = new Arqueiro(35,2,1);
        Cavaleiro c = new Cavaleiro(50,3,2);

        System.out.println(a.atacar());
        System.out.println(a.mover(15));
        System.out.println();

        System.out.println(r.atacar());
        System.out.println(r.mover(15));
        System.out.println();

        System.out.println(c.atacar());
        System.out.println(c.mover(15));
        System.out.println();
    }
}
