/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Caneta bic = new Caneta();

        bic.abrirFechar();
        bic.definirNivelTinta(67);
        bic.definirDesenho(19);

        System.out.println(bic.isAberta());
        System.out.println(bic.obterNivelTinta());
        System.out.println(bic.obterDesenho());
    }
}
