/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Caneta bic = new Caneta();

        bic.abrirFechar();
        bic.definirNivelTinta(23);
        bic.definirDesenho(4);

        System.out.println("A caneta está: " + bic.isAberta());
        System.out.println("Tinta antes de desenhar: " + bic.obterNivelTinta());
        System.out.println(bic.obterDesenho());
        System.out.println("Tinta restante: " + bic.obterTintaRestante());
    }
}
