/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Contador count = new Contador();

        count.incrementarValor();
        count.incrementarValor();
        count.definirValor(8);
        count.incrementarValor();

        System.out.println(count.obterValor());
    }
}
