/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static final String SEG = "seg";
    public static final String TER = "ter";
    public static final String QUA = "qua";
    public static final String QUI = "qui";
    public static final String SEX = "sex";

    public static void main(String[] args) {

        Disciplinas d = new Disciplinas("POO", new DiasDaSemana[]{DiasDaSemana.SEGUNDA, DiasDaSemana.QUINTA});

        for (DiasDaSemana a : DiasDaSemana.values()) {
            System.out.println(a);
        }

        DiasDaSemana e = DiasDaSemana.TERCA;

//        switch (e) {
//            case SEGUNDA -> System.out.println("tem aula");
//            case TERCA -> System.out.println("N tem aula");
//            case QUARTA -> System.out.println("N tem aula");
//            case QUINTA -> System.out.println("tem aula");
//            case SEXTA -> System.out.println("N tem aula");
//        }

        SistemaSolar s = SistemaSolar.VENUS;

        for (SistemaSolar p : SistemaSolar.values()) {
            System.out.println(p

            );
        }
    }
}
