/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {

        ArrayList<String> lista = new ArrayList<>();
        ArrayList<Pessoa> agenda = new ArrayList<>();

        lista.add("POO");
        lista.add("ALG");
        lista.add("FE1");

        Pessoa p = new Pessoa("Fulano", "fln@gmail.com");
        Pessoa n = new Pessoa("Ciclano", "cln@gmail.com");
        Pessoa m = new Pessoa("Beltrano", "blt@gmail.com");

        agenda.add(p);
        agenda.add(n);
        agenda.add(m);

        //for each

//        for (String elemento : lista) {
//            System.out.println(elemento);
//        }
//
//        for (Pessoa pessoa : agenda) {
//            System.out.println(pessoa);
//        }
//
//        //lambda
//        lista.forEach(elemento->{
//            System.out.println(elemento);
//        });

        //method reference
        lista.forEach(System.out::println);

        System.out.println();

        agenda.forEach(System.out::println);
        System.out.println();

        //remover
        lista.removeIf(elemento-> elemento.equals("POO"));
        lista.forEach(System.out::println);

        System.out.println();

        agenda.removeIf(elemento-> elemento.getNome().equals("Fulano"));
        agenda.forEach(System.out::println);

    }
}
